assets:
  sources:
    - _assets
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

keep_files: ['assets/stylesheets/fonts']

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - node_modules/*

ga_analytics: UA-XXXXXXXX-X

gems:
  - jekyll-assets
  - jekyll-sitemap

name: gov_au_transitions

permalink: pretty

url: # add site url
